version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:db
    environment:
      MYSQL_HOST: localhost
      MYSQL_USER: dev
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: devdb
    env_file:
      - .env

  db:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: dev
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: devdb
    env_file:
      - .env

volumes:
  mysql-data: